# ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: apiproxy
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list"]
---
# ClusterRoleBinding...
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: apiproxy
subjects:
  - kind: ServiceAccount
    name: apiproxy
    namespace: default
roleRef:
  kind: ClusterRole
  name: apiproxy
  apiGroup: rbac.authorization.k8s.io
