---
# ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: pg
data: <!!CHANGE_ME!!>

---
# Secrets
apiVersion: v1
kind: Secret
metadata:
  name: pg
type: Opaque
data: <!!CHANGE_ME!!>

---
# PV
apiVersion: v1
kind: PersistentVolume
metadata:
  name: <!!CHANGE_ME!!>
  labels:
    store: db
    type: spindle
spec:
  storageClassName: <!!CHANGE_ME!!>
  persistentVolumeReclaimPolicy: <!!CHANGE_ME!!>
  capacity:
    storage: <!!CHANGE_ME!!>
  accessModes:
    - <!!CHANGE_ME!!>
  hostPath:
    path: <!!CHANGE_ME!!>
---
# PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: <!!CHANGE_ME!!>
spec:
  storageClassName: <!!CHANGE_ME!!>
  accessModes:
    - <!!CHANGE_ME!!>
  resources:
    requests:
      storage: <!!CHANGE_ME!!>
  selector:
    matchLabels:
      store: <!!CHANGE_ME!!>
    # NOTE: Use expression to select pv if type = spindle or raid
    matchExpressions: <!!CHANGE_ME!!>
---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pg
  template:
    metadata:
      labels:
        app: pg
    spec:
      containers:
        - name: pg
          image: postgres:9.6.2-alpine
          env:
            - name: POSTGRES_USER
              valueFrom: <!!CHANGE_ME!!>
            - name: POSTGRES_PASSWORD
              valueFrom: <!!CHANGE_ME!!>
          ports:
            - name: client
              containerPort: <!!CHANGE_ME!!>
          resources:
            requests:
              memory: 128Mi
              cpu: 300m
            limits:
              memory: 256Mi
              cpu: 500m
          volumeMounts:
            - name: <!!CHANGE_ME!!>
              mountPath: <!!CHANGE_ME!!>
      volumes:
        - name: <!!CHANGE_ME!!>
          persistentVolumeClaim:
            claimName: <!!CHANGE_ME!!>
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: pg
spec:
  selector:
    app: pg
  type: NodePort
  ports:
    - port: 5432
      nodePort: 30543
